# Generated by Django 4.2 on 2023-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='latitude',
            field=models.FloatField(default='51.531017363425065'),
        ),
        migrations.AddField(
            model_name='truck',
            name='longitude',
            field=models.FloatField(default='-0.156907085362684'),
        ),
    ]
