# Generated by Django 4.2 on 2023-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.TextField(max_length=1000),
        ),
    ]
