# Generated by Django 4.2 on 2023-04-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='start_date',
        ),
        migrations.AddField(
            model_name='truck',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
