# Generated by Django 4.2 on 2023-04-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
