# Generated by Django 4.2 on 2023-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='truck',
            name='menu',
            field=models.ManyToManyField(default='', related_name='trucks', to='menu.menu'),
        ),
    ]
