# Generated by Django 4.2 on 2023-04-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_remove_truck_duration_remove_truck_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='image',
        ),
    ]
