# Generated by Django 4.2 on 2023-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
