# Generated by Django 4.2 on 2023-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_remove_truck_menu_name_truck_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(default='', upload_to='api/'),
        ),
    ]
