# Generated by Django 4.2 on 2023-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_alter_truck_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='end_time',
            new_name='closed',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='start_time',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='review_count',
            new_name='reviewcount',
        ),
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
