# Generated by Django 4.2 on 2023-04-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_rename_end_time_truck_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='on_friday',
            new_name='Friday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_monday',
            new_name='Monday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_saturday',
            new_name='Saturday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_sunday',
            new_name='Sunday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_thursday',
            new_name='Thursday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_tuesday',
            new_name='Tuesday',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='on_wednesday',
            new_name='Wednesday',
        ),
    ]
