# Generated by Django 4.2 on 2023-04-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
    ]
