<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-23 16:46
=======
# Generated by Django 4.2 on 2023-04-22 19:10
>>>>>>> 078212006b22fc6fa347df84094bdf8e9b7be752

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(max_length=20)),
            ],
        ),
    ]
