# Generated by Django 4.2 on 2023-04-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='truck_id',
            new_name='truck_pk',
        ),
    ]
