# Generated by Django 4.2 on 2023-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_truck_id_menu_truck_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='truck_pk',
            new_name='truck_id',
        ),
    ]
